create table if not exists public.challenge_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  username text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day integer not null check (day between 1 and 100),
  challenge_date date not null,
  learn integer not null default 0 check (learn between 0 and 2),
  build integer not null default 0 check (build between 0 and 3),
  tasks integer not null default 0 check (tasks between 0 and 2),
  doc integer not null default 0 check (doc between 0 and 1),
  github integer not null default 0 check (github between 0 and 1),
  consistency integer not null default 0 check (consistency between 0 and 1),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, day)
);

alter table public.challenge_profiles enable row level security;
alter table public.challenge_days enable row level security;

drop policy if exists "profiles_public_read" on public.challenge_profiles;
create policy "profiles_public_read" on public.challenge_profiles for select using (true);

drop policy if exists "profiles_own_insert" on public.challenge_profiles;
create policy "profiles_own_insert" on public.challenge_profiles for insert with check (auth.uid() = id);

drop policy if exists "profiles_own_update" on public.challenge_profiles;
create policy "profiles_own_update" on public.challenge_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "days_public_read" on public.challenge_days;
create policy "days_public_read" on public.challenge_days for select using (true);

drop policy if exists "days_own_insert" on public.challenge_days;
create policy "days_own_insert" on public.challenge_days for insert with check (auth.uid() = user_id);

drop policy if exists "days_own_update" on public.challenge_days;
create policy "days_own_update" on public.challenge_days for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "days_own_delete" on public.challenge_days;
create policy "days_own_delete" on public.challenge_days for delete using (auth.uid() = user_id);
